replicaCount: 1

namespace: app

image:
  repository: 826784631306.dkr.ecr.ap-south-1.amazonaws.com/hello-world
  pullPolicy: IfNotPresent
  tag: "5f9aaf5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 70m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  periodSeconds: 10
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /healthz
    port: http
  periodSeconds: 5
  failureThreshold: 12

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
