replicaCount: 1

image:
  repository: 826784631306.dkr.ecr.ap-south-1.amazonaws.com/hello-world
  tag: "5f9aaf5"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"

containerPort: 8080

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 70m
    memory: 64Mi

probes:
  liveness:
    path: /healthz
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /healthz
    periodSeconds: 10
    failureThreshold: 3
  startup:
    path: /healthz
    periodSeconds: 5
    failureThreshold: 12

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1
